feat: add feature to get inherited member for project/group
python-gitlab/python-gitlab pull request #1187
Opened 2020-09-12 09:54 UTC by Shkurupii

Hi!
This PR about feature https://github.com/python-gitlab/python-gitlab/issues/1133. Here I propose to introduce new custom managers ProjectMemberAllManager (/projects/:id/members/all/:user_id) and GroupMemberAllManager (/groups/:id/members/all/:user_id). Subsequently, in order to fetch a list or instance of members including inherited ones, you will need to:
```
project = gl.projects.get(project_id)
project.members_all.list()
project.members_all.get(member_id)
```
```
group = gl.groups.get(group_id)
group.members_all.list()
group.members_all.get(member_id)
```
I had thought about  ```group.members.all(id=group_id)``` also. But then changed my mind.
If the approach is right?

2020-09-13 17:07 UTC, nejch requested changes
Nice, I really like this. It helps remove the confusion around having `all()` methods from `/all` endpoints, `all=True` for pagination, and `"all": True` in query params where it's an attribute GitLab itself accepts.

This solution is also very similar to @chrisoldwood's proposal in https://github.com/python-gitlab/python-gitlab/issues/593.

I just have some comments on keeping backwards compatibility and naming, if you can take a look, because this can probably later be reused in some other places (maybe for runners as well) :)

2020-09-14 12:58 UTC, Shkurupii commented
Agree, I thought about backward compatibility right after made a PR. But decided to wait for a review, because in any way, there were more questions than answers.

In the git log, I found RELEASE_NOTES.rst, where such things like mine need to be reflected. Who will manage that, I?

2020-09-14 13:09 UTC, Shkurupii commented on tools/python_test_v4.py
> +assert len(group1.members_all.list())
I rolled back the test case [group1.members.all()](https://github.com/python-gitlab/python-gitlab/pull/1187/files#diff-4a8817e452ed84e4d3b53c2523dac89aR315) and added [MemberAllMixin](https://github.com/python-gitlab/python-gitlab/pull/1187/files#diff-d238c1fcc482be8ccce8a7ac82752d17R669) with ```register_custom_action``` and ```DeprecationWarning``` , ```ListAllMixin``` sounds very general, we won't use ```ListAllMixin``` somewhere I guess.

2020-09-14 13:35 UTC, Shkurupii commented on gitlab/v4/objects/__init__.py
> +        ("members_all", "ProjectMemberAllManager"),
I spent a few minutes scanning the GitLab API and looks GitLab doesn't tend to make its addresses natural. Anyway, I am not a python Pro, final conclusion is up to you.

2020-09-14 13:50 UTC, max-wittig commented
But why is this needed? We already have a few places, where we use `all()`

2020-09-14 14:16 UTC, nejch commented
> 
> 
> But why is this needed? We already have a few places, where we use `all()`

For me the `all()` method is problematic, because it means you can't implement the GET `/resource/all/<resource-id>`  endpoints cleanly (at least from what I've seen - e.g. this endpoint https://docs.gitlab.com/ee/api/members.html#get-a-member-of-a-group-or-project-including-inherited-members), as this can currently only return lists. Maybe by adding the ID param to it but `members.all(id=123)` also seems inconsistent with the `list()/get()` from other managers?

It's weird that GitLab added these endpoints separately, but I guess they might add them to other resources. The other place where I've found it used is with runners and there is also a similar issue open for that. Visually it's also a bit confusing, you need to do `gitlab project-member all --all`/`project.members.all(all=True)` to combine pagination and this list 😁 and then gitlab somtimes also accepts an `all` param 🤦

2020-09-16 16:18 UTC, Shkurupii commented
Hi! I think we're going to have to agree to disagree.
@max-wittig, how you would see the implementation of /projects/:id/members/all/:user_id?

2021-03-11 17:07 UTC, JacobHenner commented
Hello,

Was just about to implement this when I found the PR. Is this still under consideration?

2021-03-14 18:22 UTC, nejch commented
> Hello,
> 
> Was just about to implement this when I found the PR. Is this still under consideration?

Yes this is still relevant IMO so people can use the endpoint properly for individual users with `get()`. This PR just needs to be rebased first because we had a lot of refactoring recently, @Shkurupii let us know if you need help or if we should rebase

2021-03-15 16:30 UTC, closed without merging