WIP: Feature/project merge request approval rules
python-gitlab/python-gitlab pull request #1200
Opened 2020-09-29 23:34 UTC by robinson96

Addresses #1199.

2020-10-12 15:44 UTC, max-wittig commented
Hi @robinson96 thanks for the MR! Would you mind to add some docs and tests to this? I can't really test EE features, but I will take a look based on your docs!

2020-10-13 15:06 UTC, robinson96 commented
I will certainly add docs. I too lack a great way to do EE testing, I develop [GRAPE](https://github.com/LLNL/GRAPE),  which has some features for maintaining pull requests. It works in that context. (branch unfortunately is on a repo hosting service that is not public).

2020-10-13 15:07 UTC, robinson96 commented
> 
> 
> Hi @robinson96 thanks for the MR! Would you mind to add some docs and tests to this? I can't really test EE features, but I will take a look based on your docs!

I will certainly add docs. I too lack a great way to do EE testing, I develop [GRAPE](https://github.com/LLNL/GRAPE),  which has some features for maintaining pull requests. It works in that context. (branch unfortunately is on a repo hosting service that is not public).

2020-10-14 15:06 UTC, robinson96 commented
@max-wittig , I'm trying to find [test_merge_requests.py](https://travis-ci.org/github/python-gitlab/python-gitlab/jobs/735540249#L266) so I can modify it to add appropriate tests, but am coming up short. (My python testing skills are still developing). Any hints on where to be looking? (tools/functional/api/ only has a few of the files that Travis appears to be exercising...)

2020-10-14 15:25 UTC, max-wittig commented
Our unittests are here: https://github.com/python-gitlab/python-gitlab/tree/master/gitlab/tests/objects

And functional tests are here: https://github.com/python-gitlab/python-gitlab/tree/master/tools/functional/api

For this, it's only possible to add unit tests, as we run the functional tests against GitLab Core

2020-10-15 14:42 UTC, robinson96 commented
> 
> 
> Our unittests are here: https://github.com/python-gitlab/python-gitlab/tree/master/gitlab/tests/objects
> 
> And functional tests are here: https://github.com/python-gitlab/python-gitlab/tree/master/tools/functional/api
> 
> For this, it's only possible to add unit tests, as we run the functional tests against GitLab Core

Thanks. Tests are added!

2020-10-19 15:37 UTC, robinson96 commented
> 
> 
> > Our unittests are here: https://github.com/python-gitlab/python-gitlab/tree/master/gitlab/tests/objects
> > And functional tests are here: https://github.com/python-gitlab/python-gitlab/tree/master/tools/functional/api
> > For this, it's only possible to add unit tests, as we run the functional tests against GitLab Core
> 
> Thanks. Tests are added!

@max-wittig - any other concerns with this PR?

2020-10-19 15:42 UTC, max-wittig requested changes
Ah yes sorry I forgot to press the submit review button

2020-10-20 16:46 UTC, robinson96 commented on docs/gl_objects/mr_approvals.rst
> +	       }
@max-wittig  your edits have been pushed

2020-10-22 14:15 UTC, robinson96 commented
@max-wittig - any other concerns?

2020-10-28 21:27 UTC, robinson96 commented
@max-wittig - any other concerns with this branch?

2020-10-29 09:58 UTC, merged

2020-10-29 09:59 UTC, max-wittig commented
thanks for the PR and sorry for the time it took to merge

2020-10-29 14:42 UTC, robinson96 commented
@max-wittig - no worries and thanks for walking me through it!