feat: add project audit endpoint
python-gitlab/python-gitlab pull request #1308
Opened 2021-02-19 00:32 UTC by Sineaggi

Similar to #949 but specific to [project audit events](https://docs.gitlab.com/ee/api/audit_events.html#project-audit-events).

No previous issues for this exist.

The code was tested to verify it works.

2021-02-19 06:59 UTC, nejch requested changes
Thanks a lot for this @Sineaggi! Just one small comment.

BTW - It might make sense to separate this into its own module, `audit_events.py`. Looking at the upstream docs, we also have instance and group audit events, so this could be expanded at a later point, and look something like the variables module:

https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/v4/objects/variables.py

EDIT: I realize now that the current instance-level audit events were put into `events.py`, but they seem to have their own section in gitlab's api, so moving them together into `audit_events.py` might still make sense.

Then import the project-specific classes in `projects.py`.

If you feel like it, you could also add some unit tests for this as a sanity check, using the example responses from your API link as mocks. Have a look at the existing unit tests: https://github.com/python-gitlab/python-gitlab/tree/master/gitlab/tests/objects

Thanks again!

2021-02-19 06:59 UTC, nejch commented on gitlab/v4/objects/projects.py
> +class ProjectAuditManager(ListMixin, RESTManager):
Based on the upstream docs, this endpoint supports both single + all events endpoint. We have a convenience `RetrieveMixin` for endpoitns that support both .get() and .list():

```suggestion
class ProjectAuditManager(RetrieveMixin, RESTManager):
```

2021-02-19 21:07 UTC, Sineaggi commented
@nejch code moved to `audit_events.py`, moved to `RetrieveMixin`, added tests that execute both .get() and .list()

2021-02-20 11:47 UTC, nejch reviewed
Thanks again! Just found a little copy/paste leftover, I can push this.

2021-02-20 11:47 UTC, nejch commented on gitlab/tests/objects/test_audit_events.py
> +    r"http://localhost/api/v4/(((groups|projects)/1)|(admin/ci))/audit_events"
```suggestion
    r"http://localhost/api/v4/((groups|projects)/1/)audit_events"
```

2021-02-20 11:47 UTC, nejch commented on gitlab/tests/objects/test_audit_events.py
> +    rf"http://localhost/api/v4/(((groups|projects)/1)|(admin/ci))/audit_events/{id}"
```suggestion
    rf"http://localhost/api/v4/((groups|projects)/1/)audit_events/{id}"
```

2021-02-20 12:04 UTC, nejch approved these changes

2021-02-20 12:04 UTC, merged