chore: remove usage of 'from ... import *'
python-gitlab/python-gitlab pull request #1319
Opened 2021-02-22 23:28 UTC by JohnVillalovos

2021-02-23 00:14 UTC, JohnVillalovos commented
I updated the files using this script:

```
#!/usr/bin/python3 -ttu
import argparse
import re
import sys


def main() -> int:
    args = parse_args()

    fixup_file(filename=args.filename)
    return 0


def fixup_file(*, filename: str):
    content = []
    with open(filename, "r") as in_file:
        for line in in_file.readlines():
            line = line.rstrip()
            if line.startswith("import gitlab.base"):
                print("This file seems to already have been processed. Exiting")
                return
            if line.startswith("import gitlab.mixins"):
                print("This file seems to already have been processed. Exiting")
                return
            line = fixed_line(line=line)
            content.append(line)

    with open(filename, "w") as out_file:
        for line in content:
            print(line, file=out_file)


def fixed_line(*, line: str) -> str:
    if line.startswith("from gitlab.base import"):
        line = "import gitlab.base"

    if line.startswith("from gitlab.mixins import"):
        line = "import gitlab.mixins"

    for rest_obj in (
        "RESTObject",
        "RESTObjectList",
        "RESTManager",
    ):
        line = line.replace(rest_obj, "gitlab.base.{}".format(rest_obj))

    for mixin_obj in (
        "AccessRequestMixin",
        "BadgeRenderMixin",
        "CreateMixin",
        "CRUDMixin",
        "DeleteMixin",
        "DownloadMixin",
        "GetMixin",
        "GetWithoutIdMixin",
        "ListMixin",
        "NoUpdateMixin",
        "ObjectDeleteMixin",
        "ParticipantsMixin",
        "RefreshMixin",
        "RetrieveMixin",
        "SaveMixin",
        "SetMixin",
        "SubscribableMixin",
        "TimeTrackingMixin",
        "TodoMixin",
        "UpdateMixin",
        "UserAgentDetailMixin",
    ):
        line = re.sub(
            r"\b" + mixin_obj + r"\b", "gitlab.mixins.{}".format(mixin_obj), line
        )

    return line


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()

    parser.add_argument("-f", "--filename", required=True)

    args = parser.parse_args()
    return args


if "__main__" == __name__:
    sys.exit(main())
```

2021-02-23 18:49 UTC, nejch requested changes
Thanks for this @JohnVillalovos! I'm happy to see more star imports gone :grin: 

I'm just thinking that since these will be used in every new module as resources are added, perhaps we could import them all as needed into the module's namespace to keep a smaller footprint in the class definitions (and this diff would also be smaller). Especially since some of them will also grow with type annotations. Like this:

https://github.com/encode/httpx/blob/0f280af8b170ed5cc48c12a894f71a8b5762f748/httpx/_client.py#L34-L47 and
https://github.com/encode/httpx/blob/0f280af8b170ed5cc48c12a894f71a8b5762f748/httpx/__init__.py#L6-L35

And similar in requests, although I prefer the above formatting in httpx (black probably won't let us do otherwise anyway :smile: ):

https://github.com/psf/requests/blob/bdc00eb0978dd3cdd43f7cd1f95ced7aa75fab39/requests/__init__.py#L124-L128

I think this would be a bit more readable for future contributors while still explicit. WDYT? Since you were already able to script this it might be a quick change for you :) The only downside would be adding mixins to imports as they get added to modules each time.

2021-02-23 18:53 UTC, JohnVillalovos commented
Sure. I think I could modify the script to do that...  Let me look into it when I finish my work day.

Thanks for the review!

2021-02-25 18:16 UTC, nejch approved these changes

2021-02-25 18:16 UTC, merged

2021-02-25 18:18 UTC, JohnVillalovos commented
Sweet. Less 'import *' in the code 😊  Thanks for the merge!