feat(users): add follow/unfollow API
python-gitlab/python-gitlab pull request #1333
Opened 2021-02-25 21:38 UTC by max-wittig

2021-02-26 21:11 UTC, max-wittig commented on docs/gl_objects/users.rst
> +    user.following_users.list()
@nejch I couldn't use `following` and `followers` directly, as it has the same name as it's user attribute.

2021-02-26 21:11 UTC, max-wittig commented on docs/gl_objects/users.rst
> +    user.following_users.list()
What do you think about this naming?

2021-02-26 21:15 UTC, max-wittig commented on gitlab/tests/objects/test_users.py
> +    user.follow()
sadly in the test case only the `dict` is returned, so I cannot really assert the attributes of the `User` object.

Any ideas how to convert this to a `User` in the tests? It does work normally

2021-02-27 12:02 UTC, nejch requested changes
Cool! It all looks good to me, just that little docstring return (unless you want to return a User, see other thread).

2021-02-27 15:33 UTC, max-wittig commented on gitlab/tests/objects/test_users.py
> +    user.follow()
Okay that makes sense. Let's keep the conventions then.

2021-02-27 15:34 UTC, max-wittig commented on docs/gl_objects/users.rst
> +    user.following_users.list()
Then let's keep the clearer name I guess 😄

2021-02-28 07:48 UTC, nejch approved these changes

2021-02-28 07:48 UTC, merged