chore: have flake8 check the entire project
python-gitlab/python-gitlab pull request #1429
Opened 2021-04-29 15:22 UTC by JohnVillalovos

Have flake8 run at the top-level of the projects instead of just the
gitlab directory.

2021-04-29 22:59 UTC, max-wittig commented on tools/functional/api/test_issues.py
> +    _ = project.labels.create({"name": "label2", "color": "#aabbcc"})
```suggestion
project.labels.create({"name": "label2", "color": "#aabbcc"})
```

2021-04-29 22:59 UTC, max-wittig commented on tools/functional/api/test_merge_requests.py
> +    _ = project.branches.create({"branch": source_branch, "ref": "master"})
```suggestion
    project.branches.create({"branch": source_branch, "ref": "master"})
```

2021-04-29 23:00 UTC, max-wittig commented on tools/functional/api/test_releases.py
> +    _ = release.links.create(link_data)
```suggestion
    release.links.create(link_data)
```

2021-04-29 23:00 UTC, max-wittig commented on tools/functional/api/test_repository.py
> +    _ = commit.statuses.create({"state": "success", "sha": commit.id})
```suggestion
    commit.statuses.create({"state": "success", "sha": commit.id})
```

2021-04-29 23:00 UTC, max-wittig commented on tools/functional/api/test_repository.py
> +        _ = commit.signature()
```suggestion
        commit.signature()
```

2021-04-29 23:01 UTC, max-wittig requested changes
Nice catch!

Do we need to assign variables that we're not using to `_`?

2021-04-29 23:06 UTC, JohnVillalovos commented
> 
> 
> Nice catch!
> 
> Do we need to assign variables that we're not using to `_`?

No. The only reason I had for doing that was to make it clear that the call returns something.

I was undecided if I should just delete the assignment or use `_`. So I went with `_` 😀

But I will re-do it and delete the assignments.

2021-04-30 07:16 UTC, max-wittig commented
If we want to check, if it's returning something we should assert instead. But I think this is already checked somewhere else.

You can also apply the suggestions and I squash after, if you like 😃

2021-04-30 14:09 UTC, JohnVillalovos commented on tools/functional/api/test_issues.py
> +    _ = project.labels.create({"name": "label2", "color": "#aabbcc"})
Done

2021-04-30 14:09 UTC, JohnVillalovos commented on tools/functional/api/test_releases.py
> +    _ = release.links.create(link_data)
Done

2021-04-30 14:09 UTC, JohnVillalovos commented on tools/functional/api/test_repository.py
> +        _ = commit.signature()
Done

2021-04-30 14:10 UTC, JohnVillalovos commented on tools/functional/api/test_repository.py
> +    _ = commit.statuses.create({"state": "success", "sha": commit.id})
Done

2021-04-30 14:10 UTC, JohnVillalovos commented on tools/functional/api/test_merge_requests.py
> +    _ = project.branches.create({"branch": source_branch, "ref": "master"})
Done

2021-04-30 14:12 UTC, JohnVillalovos commented
@max-wittig  Updated. I think I have changed everything as requested.

2021-04-30 14:27 UTC, max-wittig approved these changes

2021-04-30 14:27 UTC, merged