feat(objects): add support for Group wikis
python-gitlab/python-gitlab pull request #1484
Opened 2021-05-30 13:08 UTC by spamsch

This pull request adds support for wikis on Group level

2021-05-30 16:32 UTC, JohnVillalovos requested changes

2021-05-30 16:32 UTC, JohnVillalovos commented on docs/gl_objects/wikis.rst
Please add link to the API page:

`https://docs.gitlab.com/ee/api/group_wikis.html`

2021-05-30 16:32 UTC, JohnVillalovos commented on docs/gl_objects/wikis.rst
>      page = project.wikis.get(page_slug)
Can we also get an example of doing a "get" of a group wiki page?

And an example of creating a group wiki page too.

2021-05-30 16:33 UTC, JohnVillalovos commented
Thanks for this PR!

I left a few comments, but overall it is looking great 👍

2021-05-31 08:32 UTC, max-wittig commented
Would it be possible for you to add some unit tests as well for this?

2021-05-31 11:51 UTC, spamsch commented
> Would it be possible for you to add some unit tests as well for this?

There are no unit tests for project wikis. Not sure it makes sense to have unit tests for groups only. Could think about adding functional tests. Makes sense?

2021-05-31 12:22 UTC, nejch commented
> 
> 
> > Would it be possible for you to add some unit tests as well for this?
> 
> There are no unit tests for project wikis. Not sure it makes sense to have unit tests for groups only. Could think about adding functional tests. Makes sense?

I just triggered the workflow. Group Wikis are a Premium/EE feature so let's see if this works in the CE container 😁 And you're right, we'd need to create a new `test_wikis.py` module with a group wiki mock response for this. There are examples in other modules if the functional tests fail (if it fails, maybe add `@pytest.mark.skip` to the functional test that you added, for now)

2021-05-31 13:33 UTC, JohnVillalovos commented
FYI: Running `tox -e black` locally should resolve the black formatting issues.

2021-05-31 16:02 UTC, JohnVillalovos commented
Thanks a lot @spamsch 😊

Looks good to me. Personally I would like it if it was rebased and squashed. As right now there are six commits and one of them is a merge commit. I think it will make the project history be better if it was rebased and squashed.

Not sure what @nejch and @max-wittig  think.

2021-06-01 06:34 UTC, nejch commented
> Thanks a lot @spamsch 😊
> 
> Looks good to me. Personally I would like it if it was rebased and squashed. As right now there are six commits and one of them is a merge commit. I think it will make the project history be better if it was rebased and squashed.
> 
> Not sure what @nejch and @max-wittig  think.

Ok, i can also squash on merge and add the unit tests along with project wiki tests in a follow-up. Just not from my phone on my commute right now.. :D

2021-06-02 22:38 UTC, merged