feat: allow global retry_transient_errors
python-gitlab/python-gitlab pull request #1565
Opened 2021-08-03 11:58 UTC by javatarz

Value set on the `Gitlab` object will be used as a default in case every
subsequent API call does not provide a `retry_transient_errors`
parameter.

This allows code to be succinct and the retry policy to be set for all
calls to the `Gitlab` instance.

2021-08-03 13:24 UTC, javatarz commented
Noticed [another MR](https://github.com/python-gitlab/python-gitlab/pull/1258) that has had a failed pipeline for a while. It also did not have documentation. It made sense to make the small change from scratch and update documentation.

I have run the test locally (for my python version). I have not generated the documentation and run a visual check on the page itself yet.

2021-08-03 13:46 UTC, nejch commented
> 
> 
> Noticed [another MR](https://github.com/python-gitlab/python-gitlab/pull/1258) that has had a failed pipeline for a while. It also did not have documentation. It made sense to make the small change from scratch and update documentation.
> 
> I have run the test locally (for my python version). I have not generated the documentation and run a visual check on the page itself yet.
> 
> Does anyone know what it would take for the pipelines to run and provide feedback? Do the tests and linters not run on the PR?

Thanks for the contribution @javatarz! I've just triggered the workflow, it needs to be approved for first-time contributors.

I'll take a look at this later tonight but yes adding a basic test would generally be good (if it makes sense here - maybe just to confirm the correct option is used depending on global/overrides) :) Thanks!

2021-08-03 16:09 UTC, javatarz commented
I had looked for tests around this and there were none. I can see a test for `http_request`. I'll add a couple of tests for

1. verifying the default behaviour (when `retry_transient_errors` is not provided)
2. verifying how `retry_transient_errors` works (missing test case)
3. verifying the default value gets applied
4. verifying that the default value can be overridden

Please don't merge this MR, I'll be back in a few hours with tests!

2021-08-03 17:36 UTC, javatarz commented
I have added the missing tests and update the documentation a bit. Here's what the documentation looks like now (after rendering)

![Transient Errors documentation update](https://user-images.githubusercontent.com/911203/128059987-0e776534-f392-454a-94c3-7e9f4726e957.png)

2021-08-05 19:14 UTC, nejch commented
Hey @javatarz finally had a chance to look at this properly, thanks again, looks great!

This looks like a good candidate to be added to global (or per-server) config in the configuration file to keep it consistent with existing files. You can take a look at the user agent (the last option added before yours) as inspiration if it helps: https://github.com/python-gitlab/python-gitlab/pull/1277/files

 (I realize `config.py` could de-duplicate a bit..). We can also do it in a follow-up, just let me know. thanks!

2021-08-10 17:35 UTC, javatarz commented
Sorry for the late response. Just had a look at `config.py` and it makes a lot of sense to add the `retry_transient_errors` to be supported through the configuration mechanism. Will push updates soon. (if you mark this as draft, you will have to trigger the pipeline again 😂)

2021-08-22 04:38 UTC, javatarz commented
@nejch: I have added changes to allow config values to be set (both globally and per gitlab connection).

Used mypy typing in test utlity functions which isn't a pattern on the file. I cannot run mypy locally (because [your fix for mypy has not been merged yet](https://github.com/python-gitlab/python-gitlab/pull/1562/files) 😞). Not sure if I have broken something.

Do you mind approving the pipeline run for me once again so I can confirm if everything is ok?
Let me know if there's any other change necessary before we can get this merged. 😃

2021-08-22 16:29 UTC, nejch commented
> @nejch: I have added changes to allow config values to be set (both globally and per gitlab connection).
> 
> Used mypy typing in test utlity functions which isn't a pattern on the file. I cannot run mypy locally (because [your fix for mypy has not been merged yet](https://github.com/python-gitlab/python-gitlab/pull/1562/files) disappointed). Not sure if I have broken something.
> 
> Do you mind approving the pipeline run for me once again so I can confirm if everything is ok?
> Let me know if there's any other change necessary before we can get this merged. smiley

Thank you @javatarz! I see mypy is not happy :) the hook fix should be ready soon. maybe you can check how it's done for the default scenario in `ssl_verify` with `getboolean()` if it helps?

2021-08-23 05:51 UTC, javatarz commented
Can confirm, `mypy` runs fine well locally! Thanks @nejch!

The build has passed locally for Python 3.9. Should be fine on other versions too. ~Do you mind triggering the pipeline for me please?~ Just noticed that someone triggered it 😄

2021-08-23 06:12 UTC, javatarz commented
Seems like the test failure is unrelated. I'm trying to run functional tests locally to confirm.

2021-08-23 06:15 UTC, nejch commented
> 
> 
> Seems like the test failure is unrelated. I'm trying to run functional tests locally to confirm.

The functional tests can be a little flaky sometimes, although I thought this was mostly fixed. I'm re-running now.

2021-08-23 06:21 UTC, javatarz commented
Dang, they passed now. Should we merge this one now or should we disable that flaky test first?

2021-08-24 15:47 UTC, javatarz commented
Are there any other steps before this change can be accepted @nejch, @JohnVillalovos?

_Picked names off of the recent people to merge/commit things_

2021-08-28 06:14 UTC, javatarz commented
@JohnVillalovos: can you have another look? I have squashed the commits into a single commit now.

2021-08-28 14:52 UTC, JohnVillalovos requested changes
Please fix the error in the docs build.

2021-08-29 09:36 UTC, javatarz commented
Thought that's a bug with my local setup. Wish the pipeline automatically ran after commits so I could get this feedback quicker.

@JohnVillalovos, @max-wittig, @nejch : Do you mind re-triggering the pipeline for me? Please let me know if there's any other review comments.

2021-08-29 13:54 UTC, JohnVillalovos approved these changes

2021-08-29 14:03 UTC, JohnVillalovos approved these changes
Looks good to me. Would like at least one other person to review.

2021-08-30 22:29 UTC, nejch approved these changes
Thanks a lot @javatarz for adding all the tests, let's finally get this merged ;) We can follow up with a tiny docs update in https://github.com/python-gitlab/python-gitlab/blob/master/docs/cli-usage.rst#content.

2021-08-30 22:30 UTC, merged

2021-12-04 06:15 UTC, javatarz commented
@nejch: is it possible to publish a new version of this artifact to pypi? I'd like to use this feature in multiple projects where I use this library. 😄

2021-12-04 10:03 UTC, nejch commented
Thanks for the ping @javatarz! I would like to and usually we have a release every 28th but I've disabled it because we have https://github.com/python-gitlab/python-gitlab/issues/1520 next, and we're dropping support for 3.6 so we thought we'd release it with 3.6 EOL, along with other breaking changes in the library.

I could maybe try cherry-picking non-breaking changes into a 2.11.0 or a pre-release branch though.

2021-12-09 17:58 UTC, Sineaggi commented
@nejch We're in a similar boat, would love to see a release cut with this particular change.