feat(ux): display project.name_with_namespace on project repr
python-gitlab/python-gitlab pull request #1996
Opened 2022-04-29 16:09 UTC by Psycojoker

This change the repr from:

```
$ gitlab.projects.get(id=some_id)
<Project id:some_id>
```

To:

```
$ gitlab.projects.get(id=some_id)
<Project id:some_id name_with_namespace:"group_name / project_name">
```

This is especially useful when working on random projects or listing of
projects since users generally don't remember projects ids.

----

On a side note I've encountered this error when trying to do a commit:

```
An unexpected error has occurred: CalledProcessError: command: ('/home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/node', '/home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    /home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/node)
    
Check the log at /home/psycojoker/.cache/pre-commit/pre-commit.log
```

I have to admit that, while I totally understand the importance of linters and good commit messages, having a hard dependency on a specific version of nodejs and glibc just do to a commit on a full python feels a bit ... intense? :sweat_smile: 

Anyway, thanks a lot for this project :heart:

2022-04-29 16:16 UTC, JohnVillalovos commented
Cool. Just as an FYI we also have a `pprint` and `pformat` functions if of any use. Not a replacement for your PR though.

```
project = gl.projects.get(id=some_id)
project.pprint()
```

2022-04-29 16:36 UTC, JohnVillalovos reviewed
Overall looks good to me. Left a minor suggestion.

Unsure if we want a unit/functional test or not for this? @nejch what do you think?

2022-04-29 16:36 UTC, JohnVillalovos commented on gitlab/v4/objects/projects.py
> +                f'{project_repr[:-1]} name_with_namespace:"{self.name_with_namespace}">'
Can use the `!r` to quote the value.

```suggestion
                f"{project_repr[:-1]} name_with_namespace:{self.name_with_namespace!r}>"
```

2022-04-29 16:37 UTC, JohnVillalovos commented
> On a side note I've encountered this error when trying to do a commit:
> 
> ```
> An unexpected error has occurred: CalledProcessError: command: ('/home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/node', '/home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
> return code: 1
> expected return code: 0
> stdout: (none)
> stderr:
>     /home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/node)
>     
> Check the log at /home/psycojoker/.cache/pre-commit/pre-commit.log
> ```
> 
> I have to admit that, while I totally understand the importance of linters and good commit messages, having a hard dependency on a specific version of nodejs and glibc just do to a commit on a full python feels a bit ... intense? 😅

So don't tell @nejch 😜  But I still don't use `pre-commit` myself. I run my tests manually for the most part and then push the PR. I let the Github CI tell me if I screwed up the commit message.

2022-04-30 07:42 UTC, nejch requested changes
Thanks @Psycojoker for this, I really like the idea to make repr more human-readable.

What do you think about generalizing it a bit to have a more declarative approach on individual resources (project, group,..) and handling the `__repr__` based on that in the `RESTObject` method, like we do with `id` using `_id_attr` now? Otherwise, we'll have to add a bunch more overrides if people want similar for other objects (or even GroupProject, UserProject.. etc).

For this, I'd introduce a `_repr_attr` on individual resources, and handle that centrally here:

https://github.com/python-gitlab/python-gitlab/blob/882fe7a681ae1c5120db5be5e71b196ae555eb3e/gitlab/base.py#L160-L164

Just to illustrate this, here's a full list (I think) of objects, a lot of them would benefit from this feature. I don't want you to do this for all of them, but if you could try to add it for every type of `*Project` we have a good start to check it works. If it's too repetitive, we could introduce mixins for this at some point, or some other more reusable way if you have any ideas :) WDYT @Psycojoker @JohnVillalovos 

```
Application
ApplicationAppearance
ApplicationSettings
AuditEvent
BroadcastMessage
CurrentUser
CurrentUserEmail
CurrentUserGPGKey
CurrentUserKey
CurrentUserStatus
DeployKey
DeployToken
Dockerfile
Event
Feature
GenericPackage
GeoNode
Gitignore
Gitlabciyml
Group
GroupAccessRequest
GroupAccessToken
GroupAuditEvent
GroupBadge
GroupBillableMember
GroupBillableMemberMembership
GroupBoard
GroupBoardList
GroupCluster
GroupCustomAttribute
GroupDeployToken
GroupDescendantGroup
GroupEpic
GroupEpicAwardEmoji
GroupEpicDiscussionNote
GroupEpicIssue
GroupEpicNote
GroupEpicNoteAwardEmoji
GroupEpicResourceLabelEvent
GroupExport
GroupHook
GroupImport
GroupIssue
GroupIssuesStatistics
GroupLabel
GroupMember
GroupMemberAll
GroupMergeRequest
GroupMilestone
GroupNotificationSettings
GroupPackage
GroupProject
GroupRunner
GroupSubgroup
GroupVariable
GroupWiki
Hook
Issue
IssuesStatistics
Key
LDAPGroup
License
List
MergeRequest
Namespace
NotificationSettings
Optional
PagesDomain
PersonalAccessToken
Project
ProjectAccessRequest
ProjectAccessToken
ProjectAdditionalStatistics
ProjectApproval
ProjectApprovalRule
ProjectArtifact
ProjectAudit
ProjectAuditEvent
ProjectBadge
ProjectBoard
ProjectBoardList
ProjectBranch
ProjectCluster
ProjectCommit
ProjectCommitComment
ProjectCommitDiscussion
ProjectCommitDiscussionNote
ProjectCommitStatus
ProjectCustomAttribute
ProjectDeployToken
ProjectDeployment
ProjectDeploymentMergeRequest
ProjectEnvironment
ProjectEvent
ProjectExport
ProjectFile
ProjectFork
ProjectHook
ProjectImport
ProjectIssue
ProjectIssueAwardEmoji
ProjectIssueDiscussion
ProjectIssueDiscussionNote
ProjectIssueLink
ProjectIssueNote
ProjectIssueNoteAwardEmoji
ProjectIssueResourceLabelEvent
ProjectIssueResourceMilestoneEvent
ProjectIssueResourceStateEvent
ProjectIssuesStatistics
ProjectJob
ProjectKey
ProjectLabel
ProjectMember
ProjectMemberAll
ProjectMergeRequest
ProjectMergeRequestApproval
ProjectMergeRequestApprovalRule
ProjectMergeRequestApprovalState
ProjectMergeRequestAwardEmoji
ProjectMergeRequestDiff
ProjectMergeRequestDiscussion
ProjectMergeRequestDiscussionNote
ProjectMergeRequestNote
ProjectMergeRequestNoteAwardEmoji
ProjectMergeRequestPipeline
ProjectMergeRequestResourceLabelEvent
ProjectMergeRequestResourceMilestoneEvent
ProjectMergeRequestResourceStateEvent
ProjectMergeTrain
ProjectMilestone
ProjectNote
ProjectNotificationSettings
ProjectPackage
ProjectPackageFile
ProjectPagesDomain
ProjectPipeline
ProjectPipelineBridge
ProjectPipelineJob
ProjectPipelineSchedule
ProjectPipelineScheduleVariable
ProjectPipelineTestReport
ProjectPipelineTestReportSummary
ProjectPipelineVariable
ProjectProtectedBranch
ProjectProtectedTag
ProjectPushRules
ProjectRegistryRepository
ProjectRegistryTag
ProjectRelease
ProjectReleaseLink
ProjectRemoteMirror
ProjectRunner
ProjectService
ProjectSnippet
ProjectSnippetAwardEmoji
ProjectSnippetDiscussion
ProjectSnippetDiscussionNote
ProjectSnippetNote
ProjectSnippetNoteAwardEmoji
ProjectTag
ProjectTrigger
ProjectUser
ProjectVariable
ProjectWiki
RepositoryMixin
Runner
RunnerJob
Snippet
StarredProject
Todo
Topic
User
UserActivities
UserCustomAttribute
UserEmail
UserEvent
UserGPGKey
UserImpersonationToken
UserKey
UserMembership
UserPersonalAccessToken
UserProject
UserStatus
Variable
```

2022-04-30 08:14 UTC, nejch commented
> > On a side note I've encountered this error when trying to do a commit:
> > ```
> > An unexpected error has occurred: CalledProcessError: command: ('/home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/node', '/home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
> > return code: 1
> > expected return code: 0
> > stdout: (none)
> > stderr:
> >     /home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/psycojoker/.cache/pre-commit/repox1_osb0o/node_env-default/bin/node)
> >     
> > Check the log at /home/psycojoker/.cache/pre-commit/pre-commit.log
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have to admit that, while I totally understand the importance of linters and good commit messages, having a hard dependency on a specific version of nodejs and glibc just do to a commit on a full python feels a bit ... intense? sweat_smile
> 
> So don't tell @nejch stuck_out_tongue_winking_eye But I still don't use `pre-commit` myself. I run my tests manually for the most part and then push the PR. I let the Github CI tell me if I screwed up the commit message.

About pre-commit - sorry to hear that. Generally the idea of `pre-commit` is to handle all of its environments for any kind of tool regardless of language and avoid exactly the type of issue you have here. But looks like that comes with hiccups (https://github.com/pre-commit/pre-commit/issues/2351). I'll change to `commitizen` based on your feedback which is python native, though it'll still be managed by pre-commit's env so we might get similar issues still.

We kind of do need pre-commit or something like that if we keep adding more linters and nitpicky rules though. Otherwise people will push a lot of failing code and it creates more noise for followers and extra effort, especially with new contributors where every push needs approval for CI to run.

The other option is that we calm down with the linting a bit and make things looser. But the commit messages at least are nice, as it makes our release process really smooth and we can bring out new versions much quicker if needed :)

2022-04-30 16:26 UTC, nejch commented
I've started https://github.com/python-gitlab/python-gitlab/pull/1998 to address the pre-commit issue. We can also just merge this as is and work on refactoring after, just let us know @Psycojoker if you'd like to try yourself already. :)

2022-05-07 19:04 UTC, nejch commented
Ok, so let's get this in to have the feature and I'll rework it based on my comment in a follow-up.

2022-05-07 19:05 UTC, merged