Support downloading archive subpaths
python-gitlab/python-gitlab pull request #2199
Opened 2022-07-28 16:35 UTC by orf

https://docs.gitlab.com/ee/api/repositories.html#get-file-archive

The archive endpoint supports a `path` argument. This change adds support for it.

2022-07-28 16:41 UTC, JohnVillalovos requested changes

2022-07-28 16:41 UTC, JohnVillalovos commented on gitlab/v4/objects/repositories.py
> +        path: str = None,
```suggestion
        path: Optional[str] = None,
```

2022-07-28 16:41 UTC, JohnVillalovos commented on gitlab/v4/objects/repositories.py
> +        if path:
```suggestion
        if path is not None:
```

2022-07-28 17:22 UTC, JohnVillalovos approved these changes

2022-07-28 17:23 UTC, JohnVillalovos commented
@orf Thanks for the contribution!

2022-07-28 17:30 UTC, JohnVillalovos commented on gitlab/v4/objects/repositories.py
> +        if path is not None:
Will need to change the name of the other `path` variable on line 232 and on line 241.

2022-07-28 17:30 UTC, JohnVillalovos commented on gitlab/v4/objects/repositories.py
> +        if path is not None:
Maybe to `url_path`

2022-07-28 17:46 UTC, JohnVillalovos requested changes
Looks like conflict with the pre-existing `path` variable.

2022-07-29 09:10 UTC, nejch commented
@JohnVillalovos for later: we could potentially also prefix these internal python-gitlab variables in the mixins and custom methods to always avoid clashes with GitLab API attributes. So this would be `_path` here for example. Not sure how ugly that would get.

@orf sometimes our variables happen to overlap with upstream API attributes hence the suggestion.

```diff
diff --git a/gitlab/v4/objects/repositories.py b/gitlab/v4/objects/repositories.py
index 8f99e5d..b8dbdd8 100644
--- a/gitlab/v4/objects/repositories.py
+++ b/gitlab/v4/objects/repositories.py
@@ -229,16 +229,16 @@ class RepositoryMixin(_RestObjectBase):
         Returns:
             The binary data of the archive
         """
-        path = f"/projects/{self.encoded_id}/repository/archive"
+        url_path = f"/projects/{self.encoded_id}/repository/archive"
         if format:
-            path += "." + format
+            url_path += "." + format
         query_data = {}
         if sha:
             query_data["sha"] = sha
         if path is not None:
             query_data["path"] = path
         result = self.manager.gitlab.http_get(
-            path, query_data=query_data, raw=True, streamed=streamed, **kwargs
+            url_path, query_data=query_data, raw=True, streamed=streamed, **kwargs
         )
         if TYPE_CHECKING:
             assert isinstance(result, requests.Response)
```

2022-07-29 10:59 UTC, orf commented
Thank you both! I've applied your suggestions 🙏

2022-07-29 11:21 UTC, nejch approved these changes

2022-07-29 11:31 UTC, nejch commented
I guess we can get this one in, I hope you don't mind @JohnVillalovos ;) 

@orf thanks again! I think I recognized your username from the loguru saga, fun popcorn material. :)

2022-07-29 11:31 UTC, merged

2022-07-29 14:49 UTC, JohnVillalovos commented
> I guess we can get this one in, I hope you don't mind @JohnVillalovos ;)

Thanks for reviewing it @nejch !