fix: use epic id instead of iid for epic notes
python-gitlab/python-gitlab pull request #2314
Opened 2022-10-16 13:42 UTC by Shreya-7

fixes #2234
Corresponding GitLab issue: https://gitlab.com/gitlab-org/gitlab/-/issues/351656 

This PR also fixes the same issue related to epic discussion notes, GitLab API ref: https://docs.gitlab.com/ee/api/discussions.html#epics

2022-10-16 13:48 UTC, Shreya-7 commented
@nejch can you review this PR?

2022-10-16 15:00 UTC, nejch requested changes
Thanks a lot, looking great! just one little note on the testing, which is mostly an issue with our legacy testing.

2022-10-16 17:59 UTC, nejch commented on tests/functional/ee-test.py
> +assert len(EPIC_NOTES == len(epic.notes.list()))
Actually, I don't want to block you here. We can refactor this legacy code in a separate PR.

2022-10-16 18:01 UTC, nejch approved these changes

2022-10-16 18:03 UTC, merged

2022-10-17 01:11 UTC, Shreya-7 commented on tests/functional/ee-test.py
> +assert len(EPIC_NOTES == len(epic.notes.list()))
@nejch thanks for the merge! I’d be happy to take a shot at this as a separate issue - do we have  something tracking this?

2022-10-17 20:14 UTC, nejch commented on tests/functional/ee-test.py
> +assert len(EPIC_NOTES == len(epic.notes.list()))
@Shreya-7 ah nice! Well, I already started https://github.com/python-gitlab/python-gitlab/pull/2317 for this, it was a bit more involved in the end as I started migrating all the legacy stuff.

But if you're interested (especially if you're doing hacktoberfest currently, we have the label enabled), you can take a look at issues with `help wanted` or `EE` labels. EE requests are a bit slower on our side as some of us here don't use Premium/Ultimate, so definitely something we could use help with.

Or just find some easy picks in the general issue list as well, I'm sure there's some low-hanging fruit :)