Added ability to get history of pipelines executed for a give n scheduled pipeline
python-gitlab/python-gitlab pull request #2342
Opened 2022-10-24 07:12 UTC by svermeulen

2022-10-24 07:55 UTC, nejch requested changes
Thanks a lot for the contribution @svermeulen! The commit message will need a little `--amend` as we generate changelogs from these - see https://github.com/python-gitlab/python-gitlab/blob/main/CONTRIBUTING.rst#commit-message-guidelines.

I added a small note. 

It'd be great if you could also add a little example here:  
https://github.com/python-gitlab/python-gitlab/blob/main/docs/gl_objects/pipelines_and_jobs.rst#examples-2

And if you're comfortable writing pytest tests, I'd also add a unit test for this here:  
https://github.com/python-gitlab/python-gitlab/blob/main/tests/unit/objects/test_pipeline_schedules.py

If not, just let me know and we'll add the tests as a follow-up so we can get this merged for the release on the 28th. Thanks again!

2022-10-24 07:55 UTC, nejch commented on gitlab/v4/objects/pipelines.py
> +    pipelines: ProjectPipelineSchedulePipelinesManager
We can use the singular for the managers here I think. Also `id` should be enough, the encoding is done elsewhere:

```suggestion
class ProjectPipelineSchedulePipelineManager(ListMixin, RESTManager):
    _path = "/projects/{project_id}/pipeline_schedules/{pipeline_schedule_id}/pipelines"
    _obj_cls = ProjectPipeline
    _from_parent_attrs = {"project_id": "project_id", "pipeline_schedule_id": "id"}


class ProjectPipelineSchedule(SaveMixin, ObjectDeleteMixin, RESTObject):
    variables: ProjectPipelineScheduleVariableManager
    pipelines: ProjectPipelineSchedulePipelineManager
```

2022-10-26 06:57 UTC, nejch commented
@svermeulen we'll have a release scheduled in 2 days so we can potentially merge this in without the tests/docs if you look at the  notes above, and I'll do the rest as follow-up :)

2022-12-04 10:00 UTC, nejch commented
Hi @svermeulen! Let us know if you'd like to finish this PR, or if we should push to your branch to get this merged (either way you'll be credited as the commit author). Thanks again for the contribution!

2022-12-05 04:11 UTC, svermeulen commented
Hi @nejch 
Sorry, I haven't been able to find the time since sending the original PR here and not sure how soon that will change, so if you or someone else wants to take it over please feel free!

2022-12-06 00:17 UTC, nejch commented on gitlab/v4/objects/pipelines.py
> +    pipelines: ProjectPipelineSchedulePipelinesManager
Done in 202bbdd0da5baf138d7e794451d49eccb623559f.

2022-12-06 00:18 UTC, nejch approved these changes
LGTM, did a little fix up and I've added tests in 2db5543313c424b67dcfff34707dba3a3a52b1ee so would need another pair of eyes for merge.

2022-12-10 13:57 UTC, nejch commented
@lmilbaum we are a bit short on maintainers at the moment, if you'd like to give this one a look let me know and I'll merge once we have one more approval ;)

2022-12-11 02:46 UTC, lmilbaum approved these changes
LGTM

2022-12-11 04:44 UTC, merged