feat: add resource iteration events
python-gitlab/python-gitlab pull request #2393
Opened 2022-11-24 12:59 UTC by oliverbl

* see https://docs.gitlab.com/ee/api/resource_iteration_events.html

2022-11-26 16:02 UTC, nejch requested changes
Thanks a lot for the contribution @oliverbl, very clean PR! Just a tiny note on style. Also would you be able to add a sentence in the examples here?

https://github.com/python-gitlab/python-gitlab/blob/main/docs/gl_objects/projects.rst#examples

2022-11-26 16:02 UTC, nejch commented on tests/unit/objects/test_resource_iteration_events.py
> +    iteration_events = project_issue.resourceiterationevents.list()
To go with the above:
```suggestion
    iteration_events = project_issue.resource_iteration_events.list()
```

2022-11-26 16:02 UTC, nejch commented on tests/unit/objects/test_resource_iteration_events.py
> +    iteration_event = project_issue.resourceiterationevents.get(1)
```suggestion
    iteration_event = project_issue.resource_iteration_events.get(1)
```

2022-12-01 09:40 UTC, oliverbl commented
> Thanks a lot for the contribution @oliverbl, very clean PR! Just a tiny note on style. Also would you be able to add a sentence in the examples here?
> 
> https://github.com/python-gitlab/python-gitlab/blob/main/docs/gl_objects/projects.rst#examples


I'm not sure which is the correct place for the documentation of iteration events. Currenty iteration events can only be accessed by project issues, so I added the example to the project issue documentation.

But also other events (like Milestone events) have their own documentation file

2022-12-04 10:17 UTC, nejch commented
> > Thanks a lot for the contribution @oliverbl, very clean PR! Just a tiny note on style. Also would you be able to add a sentence in the examples here?
> > https://github.com/python-gitlab/python-gitlab/blob/main/docs/gl_objects/projects.rst#examples
> 
> I'm not sure which is the correct place for the documentation of iteration events. Currenty iteration events can only be accessed by project issues, so I added the example to the project issue documentation.
> 
> But also other events (like Milestone events) have their own documentation file

Ah sorry, I sent the wrong link. That makes sense in the issues docs @oliverbl, if the events endpoints grow we can later create a separate page for them.

2022-12-04 10:18 UTC, nejch approved these changes

2022-12-04 10:20 UTC, merged