Documentation for "badges" page
python-gitlab/python-gitlab pull request #2486
Opened 2023-02-09 16:30 UTC by Soumya-Kushwaha

Fixes #2485

2023-02-09 22:54 UTC, nejch commented
Thanks for the PR @Soumya-Kushwaha! You'll just need to amend your commit message according to https://github.com/python-gitlab/python-gitlab/blob/main/CONTRIBUTING.rst#commit-message-guidelines so we have green CI. Thanks!

2023-02-09 22:55 UTC, nejch requested changes
Thanks for the PR @Soumya-Kushwaha! You'll just need to amend your commit message according to https://github.com/python-gitlab/python-gitlab/blob/main/CONTRIBUTING.rst#commit-message-guidelines so we have green CI. Thanks!

2023-02-10 18:18 UTC, Soumya-Kushwaha commented
I hope this works. Please let me know if there are further changes to be made.
I am actually new to this, so may not be accurate.

2023-02-10 19:00 UTC, JohnVillalovos commented
> I hope this works. Please let me know if there are further changes to be made. I am actually new to this, so may not be accurate.

@Soumya-Kushwaha Please do:

`git commit --amend` and then edit the commit message and save it.

Then do: `git push --force-with-lease` to push updated commit.

2023-02-11 04:23 UTC, closed without merging