fix(cli): add ability to disable SSL verification
python-gitlab/python-gitlab pull request #2717
Opened 2023-11-04 00:37 UTC by JohnVillalovos

Add a `--no-ssl-verify` option to disable SSL verification

Closes: #2714

## Changes

### Documentation and testing

Please consider whether this PR needs documentation and tests. **This is not required**, but highly appreciated:

- [ ] Documentation in the matching [docs section](https://github.com/python-gitlab/python-gitlab/tree/main/docs)
- [ ] [Unit tests](https://github.com/python-gitlab/python-gitlab/tree/main/tests/unit) and/or [functional tests](https://github.com/python-gitlab/python-gitlab/tree/main/tests/functional)

2023-11-07 14:15 UTC, nejch requested changes
Thanks a lot @JohnVillalovos! This is nice and simple but I think we might need a more general fix, WDYT?

2023-11-07 14:15 UTC, nejch commented on gitlab/cli.py
> +
I like the simplicity of this, but it doesn't fully fix #2714. We still cannot use environment variables (this is true for all of our booleans on the CLI). We'd need some kind of strtobool logic for those, and that maybe also falls back to strings for the `ssl_verify` arg. Also, the new flag doesn't have an env var equivalent this way like the others do. WDYT?

2023-11-07 15:00 UTC, JohnVillalovos commented
> Thanks a lot @JohnVillalovos! This is nice and simple but I think we might need a more general fix, WDYT?

I don't disagree that it could be better but it does handle the issue brought up in #2714  As it will allow them to disable `ssl_verify`

At the moment I'm not sure if I personally have the time to start down the path that will be required to make all environment variables work.

If someone wants to attempt it then the strtobool could be done similar to this: https://github.com/python/cpython/blob/f55cb44359821e71c29903f2152b4658509dac0d/Lib/configparser.py#L1092-L1097

2023-11-22 13:46 UTC, nejch commented
> > Thanks a lot @JohnVillalovos! This is nice and simple but I think we might need a more general fix, WDYT?
> 
> I don't disagree that it could be better but it does handle the issue brought up in #2714 As it will allow them to disable `ssl_verify`
> 
> At the moment I'm not sure if I personally have the time to start down the path that will be required to make all environment variables work.
> 
> If someone wants to attempt it then the strtobool could be done similar to this: https://github.com/python/cpython/blob/f55cb44359821e71c29903f2152b4658509dac0d/Lib/configparser.py#L1092-L1097

Sorry for the delay here, I was just thinking about whether we should introduce something that would potentially be deprecated again if we have a strtobool solution later, maybe we can go ahead with this if I don't get to it before the 28th :grin:

2023-12-13 12:18 UTC, merged