chore: add ability to set help for custom_actions. Also add help to the `project-key` action
python-gitlab/python-gitlab pull request #2881
Opened 2024-05-22 14:57 UTC by JohnVillalovos

Now when registering a custom_action can add help text if desired.

Also delete the VerticalHelpFormatter as no longer needed. When the
help value is set to `None` or some other value, the actions will get
printed vertically. Before when the help value was not set the actions
would all get put onto one line.

Add some help text for `gitlab project-key enable`. This both adds
help text and shows how to use the new `help` feature.

Example:
```
$ gitlab project-key --help
usage: gitlab project-key [-h] {list,get,create,update,delete,enable} ...

options:
  -h, --help            show this help message and exit

action:
  {list,get,create,update,delete,enable}
                        Action to execute on the GitLab resource.
    list                List the GitLab resources
    get                 Get a GitLab resource
    create              Create a GitLab resource
    update              Update a GitLab resource
    delete              Delete a GitLab resource
    enable              Enable a deploy key for the project
```

2024-05-29 20:19 UTC, nejch commented
Thanks @JohnVillalovos I haven't gotten to this in more depth, I just noticed we now have the weird inline help again which we tried to address in https://github.com/python-gitlab/python-gitlab/issues/456.. not sure if it's this PR or a regression before, btu we didn't have this in 4.5.0 so we need to investigate where it regressed..

```
resource:
  {application,application-appearance,application-settings,application-statistics,audit-event,broadcast-message,bulk-import,bulk-import-all-entity,bulk-import-entity,ci-lint,current-user,current-user-email,current-user-gpg-key,current-user-key,current-user-runner,current-user-status,deploy-key,deploy-token,dockerfile,event,feature,generic-package,geo-node,gitignore,gitlabciyml,group,group-access-request,group-access-token,group-audit-event,group-badge,group-billable-member,group-billable-member-membership,group-board,group-board-list,group-cluster,group-custom-attribute,group-deploy-token,group-descendant-group,group-epic,group-epic-award-emoji,group-epic-discussion-note,group-epic-issue,group-epic-note,group-epic-note-award-emoji,group-epic-resource-label-event,group-export,group-hook,group-import,group-invitation,group-issue,group-issues-statistics,group-iteration,group-ldap-group-link,group-label,group-member,group-member-all,group-merge-request,group-milestone,group-notification-settings,group-package,group-project,group-push-rules,group-runner,group-saml-group-link,group-service-account,group-subgroup,group-variable,group-wiki,hook,issue,issues-statistics,key,ldap-group,license,merge-request,namespace,notification-settings,pages-domain,personal-access-token,project,project-access-request,project-access-token,project-additional-statistics,project-approval,project-approval-rule,project-artifact,project-audit-event,project-badge,project-board,project-board-list,project-branch,project-ci-lint,project-cluster,project-commit,project-commit-comment,project-commit-discussion,project-commit-discussion-note,project-commit-status,project-custom-attribute,project-deploy-token,project-deployment,project-deployment-merge-request,project-environment,project-event,project-export,project-file,project-fork,project-hook,project-import,project-integration,project-invitation,project-issue,project-issue-award-emoji,project-issue-discussion,project-issue-discussion-note,project-issue-link,project-issue-note,project-issue-note-award-emoji,project-issue-resource-iteration-event,project-issue-resource-label-event,project-issue-resource-milestone-event,project-issue-resource-state-event,project-issue-resource-weight-event,project-issues-statistics,project-job,project-job-token-scope,project-key,project-label,project-member,project-member-all,project-merge-request,project-merge-request-approval,project-merge-request-approval-rule,project-merge-request-approval-state,project-merge-request-award-emoji,project-merge-request-diff,project-merge-request-discussion,project-merge-request-discussion-note,project-merge-request-draft-note,project-merge-request-note,project-merge-request-note-award-emoji,project-merge-request-pipeline,project-merge-request-resource-label-event,project-merge-request-resource-milestone-event,project-merge-request-resource-state-event,project-merge-request-reviewer-detail,project-merge-train,project-milestone,project-note,project-notification-settings,project-package,project-package-file,project-package-pipeline,project-pages-domain,project-pipeline,project-pipeline-bridge,project-pipeline-job,project-pipeline-schedule,project-pipeline-schedule-pipeline,project-pipeline-schedule-variable,project-pipeline-test-report,project-pipeline-test-report-summary,project-pipeline-variable,project-protected-branch,project-protected-environment,project-protected-tag,project-push-rules,project-registry-repository,project-registry-tag,project-release,project-release-link,project-remote-mirror,project-resource-group,project-resource-group-upcoming-job,project-runner,project-secure-file,project-service,project-snippet,project-snippet-award-emoji,project-snippet-discussion,project-snippet-discussion-note,project-snippet-note,project-snippet-note-award-emoji,project-storage,project-tag,project-trigger,project-user,project-variable,project-wiki,registry-repository,runner,runner-all,runner-job,shared-project,snippet,starred-project,todo,topic,user,user-activities,user-custom-attribute,user-email,user-event,user-gpg-key,user-impersonation-token,user-key,user-membership,user-personal-access-token,user-project,user-status,variable}
```

2024-05-29 20:28 UTC, JohnVillalovos commented
> Thanks @JohnVillalovos I haven't gotten to this in more depth, I just noticed we now have the weird inline help again which we tried to address in #456.. not sure if it's this PR or a regression before, btu we didn't have this in 4.5.0 so we need to investigate where it regressed..

This is an improvement in my mind.

So here is how it was in 4.5.0.  Where the resources get repeated twice in a very long list.

```
$ tox -e venv -- gitlab --help
venv: commands[0]> gitlab --help
usage: gitlab [-h] [--version] [-v] [-d] [-c CONFIG_FILE] [-g GITLAB] [-o {json,legacy,yaml}] [-f FIELDS] [--server-url SERVER_URL] [--ssl-verify SSL_VERIFY | --no-ssl-verify]
              [--timeout TIMEOUT] [--api-version API_VERSION] [--per-page PER_PAGE] [--pagination PAGINATION] [--order-by ORDER_BY] [--user-agent USER_AGENT]
              [--private-token PRIVATE_TOKEN | --oauth-token OAUTH_TOKEN | --job-token JOB_TOKEN] [--skip-login]
  application
  application-appearance
  application-settings
  application-statistics
  audit-event
  broadcast-message
  bulk-import
  bulk-import-all-entity
  bulk-import-entity
  ci-lint
  current-user
  current-user-email
  current-user-gpg-key
  current-user-key
  current-user-runner
  current-user-status
  deploy-key
  deploy-token
  dockerfile
  event
  feature
  generic-package
  geo-node
  gitignore
  gitlabciyml
  group
  group-access-request
  group-access-token
  group-audit-event
  group-badge
  group-billable-member
  group-billable-member-membership
  group-board
  group-board-list
  group-cluster
  group-custom-attribute
  group-deploy-token
  group-descendant-group
  group-epic
  group-epic-award-emoji
  group-epic-discussion-note
  group-epic-issue
  group-epic-note
  group-epic-note-award-emoji
  group-epic-resource-label-event
  group-export
  group-hook
  group-import
  group-invitation
  group-issue
  group-issues-statistics
  group-iteration
  group-ldap-group-link
  group-label
  group-member
  group-member-all
  group-merge-request
  group-milestone
  group-notification-settings
  group-package
  group-project
  group-push-rules
  group-runner
  group-saml-group-link
  group-subgroup
  group-variable
  group-wiki
  hook
  issue
  issues-statistics
  key
  ldap-group
  license
  merge-request
  namespace
  notification-settings
  pages-domain
  personal-access-token
  project
  project-access-request
  project-access-token
  project-additional-statistics
  project-approval
  project-approval-rule
  project-artifact
  project-audit-event
  project-badge
  project-board
  project-board-list
  project-branch
  project-ci-lint
  project-cluster
  project-commit
  project-commit-comment
  project-commit-discussion
  project-commit-discussion-note
  project-commit-status
  project-custom-attribute
  project-deploy-token
  project-deployment
  project-deployment-merge-request
  project-environment
  project-event
  project-export
  project-file
  project-fork
  project-hook
  project-import
  project-integration
  project-invitation
  project-issue
  project-issue-award-emoji
  project-issue-discussion
  project-issue-discussion-note
  project-issue-link
  project-issue-note
  project-issue-note-award-emoji
  project-issue-resource-iteration-event
  project-issue-resource-label-event
  project-issue-resource-milestone-event
  project-issue-resource-state-event
  project-issue-resource-weight-event
  project-issues-statistics
  project-job
  project-job-token-scope
  project-key
  project-label
  project-member
  project-member-all
  project-merge-request
  project-merge-request-approval
  project-merge-request-approval-rule
  project-merge-request-approval-state
  project-merge-request-award-emoji
  project-merge-request-diff
  project-merge-request-discussion
  project-merge-request-discussion-note
  project-merge-request-draft-note
  project-merge-request-note
  project-merge-request-note-award-emoji
  project-merge-request-pipeline
  project-merge-request-resource-label-event
  project-merge-request-resource-milestone-event
  project-merge-request-resource-state-event
  project-merge-request-reviewer-detail
  project-merge-train
  project-milestone
  project-note
  project-notification-settings
  project-package
  project-package-file
  project-package-pipeline
  project-pages-domain
  project-pipeline
  project-pipeline-bridge
  project-pipeline-job
  project-pipeline-schedule
  project-pipeline-schedule-pipeline
  project-pipeline-schedule-variable
  project-pipeline-test-report
  project-pipeline-test-report-summary
  project-pipeline-variable
  project-protected-branch
  project-protected-environment
  project-protected-tag
  project-push-rules
  project-registry-repository
  project-registry-tag
  project-release
  project-release-link
  project-remote-mirror
  project-resource-group
  project-resource-group-upcoming-job
  project-runner
  project-secure-file
  project-service
  project-snippet
  project-snippet-award-emoji
  project-snippet-discussion
  project-snippet-discussion-note
  project-snippet-note
  project-snippet-note-award-emoji
  project-storage
  project-tag
  project-trigger
  project-user
  project-variable
  project-wiki
  registry-repository
  runner
  runner-all
  runner-job
  shared-project
  snippet
  starred-project
  todo
  topic
  user
  user-activities
  user-custom-attribute
  user-email
  user-event
  user-gpg-key
  user-impersonation-token
  user-key
  user-membership
  user-personal-access-token
  user-project
  user-status
  variable
              ...

GitLab API Command Line Interface

options:
  -h, --help            show this help message and exit
  --version             Display the version.
  -v, --verbose, --fancy
                        Verbose mode (legacy format only) [env var: GITLAB_VERBOSE]
  -d, --debug           Debug mode (display HTTP requests) [env var: GITLAB_DEBUG]
  -c CONFIG_FILE, --config-file CONFIG_FILE
                        Configuration file to use. Can be used multiple times. [env var: PYTHON_GITLAB_CFG]
  -g GITLAB, --gitlab GITLAB
                        Which configuration section should be used. If not defined, the default selection will be used.
  -o {json,legacy,yaml}, --output {json,legacy,yaml}
                        Output format (v4 only): json|legacy|yaml
  -f FIELDS, --fields FIELDS
                        Fields to display in the output (comma separated). Not used with legacy output
  --server-url SERVER_URL
                        GitLab server URL [env var: GITLAB_URL]
  --ssl-verify SSL_VERIFY
                        Path to a CA_BUNDLE file or directory with certificates of trusted CAs. [env var: GITLAB_SSL_VERIFY]
  --no-ssl-verify       Disable SSL verification
  --timeout TIMEOUT     Timeout to use for requests to the GitLab server. [env var: GITLAB_TIMEOUT]
  --api-version API_VERSION
                        GitLab API version [env var: GITLAB_API_VERSION]
  --per-page PER_PAGE   Number of entries to return per page in the response. [env var: GITLAB_PER_PAGE]
  --pagination PAGINATION
                        Whether to use keyset or offset pagination [env var: GITLAB_PAGINATION]
  --order-by ORDER_BY   Set order_by globally [env var: GITLAB_ORDER_BY]
  --user-agent USER_AGENT
                        The user agent to send to GitLab with the HTTP request. [env var: GITLAB_USER_AGENT]
  --private-token PRIVATE_TOKEN
                        GitLab private access token [env var: GITLAB_PRIVATE_TOKEN]
  --oauth-token OAUTH_TOKEN
                        GitLab OAuth token [env var: GITLAB_OAUTH_TOKEN]
  --job-token JOB_TOKEN
                        GitLab CI job token [env var: CI_JOB_TOKEN]
  --skip-login          Skip initial authenticated API call to the current user endpoint. This may be useful when invoking the CLI in scripts. [env var: GITLAB_SKIP_LOGIN]

resource:
  application
  application-appearance
  application-settings
  application-statistics
  audit-event
  broadcast-message
  bulk-import
  bulk-import-all-entity
  bulk- [...]

2024-05-29 20:31 UTC, JohnVillalovos commented
Currently it looks like this:

```
tox -e venv -- gitlab --help
venv: commands[0]> gitlab --help
usage: gitlab [-h] [--version] [-v] [-d] [-c CONFIG_FILE] [-g GITLAB] [-o {json,legacy,yaml}] [-f FIELDS] [--server-url SERVER_URL] [--ssl-verify SSL_VERIFY | --no-ssl-verify]
              [--timeout TIMEOUT] [--api-version API_VERSION] [--per-page PER_PAGE] [--pagination PAGINATION] [--order-by ORDER_BY] [--user-agent USER_AGENT]
              [--private-token PRIVATE_TOKEN | --oauth-token OAUTH_TOKEN | --job-token JOB_TOKEN] [--skip-login]
              {application,application-appearance,application-settings,application-statistics,audit-event,broadcast-message,bulk-import,bulk-import-all-entity,bulk-import-entity,ci-lint,current-user,current-user-email,current-user-gpg-key,current-user-key,current-user-runner,current-user-status,deploy-key,deploy-token,dockerfile,event,feature,generic-package,geo-node,gitignore,gitlabciyml,group,group-access-request,group-access-token,group-audit-event,group-badge,group-billable-member,group-billable-member-membership,group-board,group-board-list,group-cluster,group-custom-attribute,group-deploy-token,group-descendant-group,group-epic,group-epic-award-emoji,group-epic-discussion-note,group-epic-issue,group-epic-note,group-epic-note-award-emoji,group-epic-resource-label-event,group-export,group-hook,group-import,group-invitation,group-issue,group-issues-statistics,group-iteration,group-ldap-group-link,group-label,group-member,group-member-all,group-merge-request,group-milestone,group-notification-settings,group-package,group-project,group-push-rules,group-runner,group-saml-group-link,group-service-account,group-subgroup,group-variable,group-wiki,hook,issue,issues-statistics,key,ldap-group,license,merge-request,namespace,notification-settings,pages-domain,personal-access-token,project,project-access-request,project-access-token,project-additional-statistics,project-approval,project-approval-rule,project-artifact,project-audit-event,project-badge,project-board,project-board-list,project-branch,project-ci-lint,project-cluster,project-commit,project-commit-comment,project-commit-discussion,project-commit-discussion-note,project-commit-status,project-custom-attribute,project-deploy-token,project-deployment,project-deployment-merge-request,project-environment,project-event,project-export,project-file,project-fork,project-hook,project-import,project-integration,project-invitation,project-issue,project-issue-award-emoji,project-issue-discussion,project-issue-discussion-note,project-issue-link,project-issue-note,project-issue-note-award-emoji,project-issue-resource-iteration-event,project-issue-resource-label-event,project-issue-resource-milestone-event,project-issue-resource-state-event,project-issue-resource-weight-event,project-issues-statistics,project-job,project-job-token-scope,project-key,project-label,project-member,project-member-all,project-merge-request,project-merge-request-approval,project-merge-request-approval-rule,project-merge-request-approval-state,project-merge-request-award-emoji,project-merge-request-diff,project-merge-request-discussion,project-merge-request-discussion-note,project-merge-request-draft-note,project-merge-request-note,project-merge-request-note-award-emoji,project-merge-request-pipeline,project-merge-request-resource-label-event,project-merge-request-resource-milestone-event,project-merge-request-resource-state-event,project-merge-request-reviewer-detail,project-merge-train,project-milestone,project-note,project-notification-settings,project-package,project-package-file,project-package-pipeline,project-pages-domain,project-pipeline,project-pipeline-bridge,project-pipeline-job,project-pipeline-schedule,project-pipeline-schedule-pipeline,project-pipeline-schedule-variable,project-pipeline-test-report,project-pipeline-test-report-summary,project-pipeline-variable,project-protected-branch,project-protected-environment,project-protected-tag,project-push-rules,project-registry-repository,project-registry-tag,project-release,project-release-link,project-remote-mirror,project-resource-group,project-resource-group-upcoming-job,project-runner,project-secure-file,project-service,project-snippet,project-snippet-award-emoji,project-snippet-discussion,project-snippet-discussion-note,project-snippet-note,project-snippet-note-award-emoji,project-storage,project-tag,project-trigger,project-user,project-variable,project-wiki,registry-repository,runner,runner-all,runner-job,shared-project,snippet,starred-project,todo,topic,user,user-activities,user-custom-attribute,user-email,user-event,user-gpg-key,user-impersonation-token,user-key,user-membership,user-personal-access-token,user-project,user-status,variable}
              ...

GitLab API Command Line Interface

options:
  -h, --help            show this help message and exit
  --version             Display the version.
  -v, --verbose, --fancy
                        Verbose mode (legacy format only) [env var: GITLAB_VERBOSE]
  -d, --debug           Debug mode (display HTTP requests) [env var: GITLAB_DEBUG]
  -c CONFIG_FILE, --config-file CONFIG_FILE
                        Configuration file to use. Can be used multiple times. [env var: PYTHON_GITLAB_CFG]
  -g GITLAB, --gitlab GITLAB
                        Which configuration section should be used. If not defined, the default selection will be used.
  -o {json,legacy,yaml}, --output {json,legacy,yaml}
                        Output format (v4 only): json|legacy|yaml
  -f FIELDS, --fields FIELDS
                        Fields to display in the output (comma separated). Not used with legacy output
  --server-url SERVER_URL
                        GitLab server URL [env var: GITLAB_URL]
  --ssl-verify SSL_VERIFY
                        Path to a CA_BUNDLE file or directory with certificates of trusted CAs. [env var: GITLAB_SSL_VERIFY]
  --no-ssl-verify       Disable SSL verification
  --timeout TIMEOUT     Timeout to use for requests to the GitLab server. [env var: GITLAB_TIMEOUT]
  --api-version API_VERSION
                        GitLab API version [env var: GITLAB_API_VERSION]
  --per-page PER_PAGE   Number of entries to return per page in the response. [env var: GITLAB_PER_PAGE]
  --pagination PAGINATION
                        Whether to use keyset or offset pagination [env var: GITLAB_PAGINATION]
  --order-by ORDER_BY   Set order_by globally [env var: GITLAB_ORDER_BY]
  --user-agent USER_AGENT
                        The user agent to send to GitLab with the HTTP request. [env var: GITLAB_USER_AGENT]
  --private-token PRIVATE_TOKEN
                        GitLab private access token [env var: GITLAB_PRIVATE_TOKEN]
  --oauth-token OAUTH_TOKEN
                        GitLab OAuth token [env var: GITLAB_OAUTH_TOKEN]
  --job-token JOB_TOKEN
                        GitLab CI job token [env var: CI_JOB_TOKEN]
  --skip-login          Skip initial authenticated API call to the current user endpoint. This may be useful when invoking the CLI in scripts. [env var: GITLAB_SKIP_LOGIN]

resource:
  {application,application-appearance,application-settings,application-statistics,audit-event,broadcast-message,bulk-import,bulk-import-all-entity,bulk-import-entity,ci-lint,current-user,current-user-email,current-user-gpg-key,current-user-key,current-user-runner,current-user-status,deploy-key,deploy-token,dockerfile,event,feature,generic-package,geo-node,gitignore,gitlabciyml,group,group-access-request,group-access-token,group-audit-event,group-badge,group-billable-member,group-billable-member-membership,group-board,group-board-list,group-cluster,group-custom-attribute,group-deploy-token,group-descendant-group,group-epic,group-epic-award-emoji,group-epic-discussion-note,group-epic-issue,group-epic-note,group-epic-note-award-emoji,group-epic-resource-label-event,group-export,group-hook,group-import,group-invitation,group-issue,group-issues-statistics,group-iteration,group-ldap-group-link,group-label,group-member,group-memb [...]

2024-05-29 20:32 UTC, JohnVillalovos commented
So I think we still have what #451 wanted to accomplish, which was to list the options vertically. We have that, and with the API end points.

2024-05-30 01:05 UTC, JohnVillalovos commented
@nejch Please let me know what you think. I might be missing things. Thanks.

2024-05-31 11:11 UTC, nejch commented
@JohnVillalovos the `usage:` part, which is what gets displayed when the user mistypes a command or doesn't explicitly ask for `--help`, is what has regressed it seems. Ideally we could deduplicate that though and just display this one. But in any case, it's not part of this PR but already on main, so shouldn't be an issue here :+1:

2024-05-31 13:46 UTC, nejch requested changes

2024-05-31 14:24 UTC, JohnVillalovos commented on tests/functional/cli/test_cli.py
> -    assert ret.returncode == 0
Done. Thanks.

2024-06-02 15:44 UTC, nejch approved these changes

2024-06-02 15:45 UTC, merged