feat: introduce related_issues to merge requests
python-gitlab/python-gitlab pull request #2996
Opened 2024-09-23 10:15 UTC by xakepnz

## Changes

- This PR introduces `related_issues` for the `merge_requests` object, returning a list of all related issues.

### Context

GitLab released `related_issues` ([official docs](https://docs.gitlab.com/ee/api/merge_requests.html#list-issues-related-to-the-merge-request)), an endpoint which collects all issues that relate to the current MR. This can be from:
- commit messages on the MR that contain issue links
- issue links commented in the MR
- issue links in the title of the MR
- issues created from discussions in the MR

See the change introduced: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/155422

#### PoC:

```sh
curl --header "PRIVATE-TOKEN: <your_access_token>" \
  --url "https://127.0.0.1:3000/api/v4/projects/7/merge_requests/1/related_issues"
```

### Documentation and testing

Both docs & tests updated

Please consider whether this PR needs documentation and tests. **This is not required**, but highly appreciated:

- [x] Documentation in the matching [docs section](https://github.com/python-gitlab/python-gitlab/tree/main/docs)
- [x] [Unit tests](https://github.com/python-gitlab/python-gitlab/tree/main/tests/unit) and/or [functional tests](https://github.com/python-gitlab/python-gitlab/tree/main/tests/functional)

2024-09-23 10:46 UTC, nejch requested changes
Thanks a lot for your contribution @xakepnz!

I just left a few initial comments to get tests green hopefully. Let me know if anything's unclear.

2024-09-23 10:46 UTC, nejch commented on tests/unit/objects/test_merge_requests.py
> +    assert mrs[0].related_issues == mr_content["related_issues"]
I'm guessing you'll want to call the method here:

```suggestion
    assert mrs[0].related_issues() == mr_content["related_issues"]
```

2024-09-23 10:46 UTC, nejch commented on tests/unit/objects/test_merge_requests.py
> +    "related_issues": [1, 2],
In reality, GitLab will respond with a complete JSON object with more details of each issue. See the example response in https://docs.gitlab.com/ee/api/merge_requests.html#list-issues-related-to-the-merge-request.

Additionally, as this is an entire new endpoint we'll need to actually mock the `/related_issues` response separately from the `resp_list_merge_requests`. Let me know if you need any help with that :bow:

2024-09-23 11:50 UTC, xakepnz commented
> Thanks a lot for your contribution @xakepnz!
> 
> I just left a few initial comments to get tests green hopefully. Let me know if anything's unclear.

Hey @nejch, thanks for the quick replies! - I ended up reverting my test before seeing your suggestions. So i've re-added it and i'm still working on Mocking the calls to `/related_issues`

You're correct, the response from GitLab API is a list of dicts containing a lot more than just the issue id's.

I'll keep working on this to try and pass CI tests.

2024-09-23 12:53 UTC, xakepnz commented
Hey @nejch should be all set now thanks!

![need-sleep](https://64.media.tumblr.com/9c25f48ae66915ffdbdc04d3646ea209/tumblr_nzempsrmyB1udh5n8o1_500.gif)

2024-09-24 11:50 UTC, nejch approved these changes
Thanks again for your contribution @xakepnz, LGTM now!

These days I'd probably prefer a manager with `.list()` which would also solve your `next(iter(..))` issues, but it's a bit of overhead in the code and I see we already have the same approach for `commits`, `closes_issues` etc.

2024-09-24 11:51 UTC, merged