feat(graphql): add async client
python-gitlab/python-gitlab pull request #3045
Opened 2024-11-25 11:43 UTC by nejch

Users have been asking for years for some kind of async support. This is pretty easy to do with the GraphQL client as we're only talking to a single endpoint so it's a good start. 

## Changes

Adds `AsyncGraphQL` and a private base client for common graphql logic. 

Related to https://github.com/python-gitlab/python-gitlab/issues/1357
Related to https://github.com/python-gitlab/python-gitlab/issues/1025

### Documentation and testing

Please consider whether this PR needs documentation and tests. **This is not required**, but highly appreciated:

- [ ] Documentation in the matching [docs section](https://github.com/python-gitlab/python-gitlab/tree/main/docs)
- [ ] [Unit tests](https://github.com/python-gitlab/python-gitlab/tree/main/tests/unit) and/or [functional tests](https://github.com/python-gitlab/python-gitlab/tree/main/tests/functional)

2024-11-25 12:32 UTC, nejch commented on gitlab/client.py
> +                )
Maybe I could put some of the error handling into the base client if you think it's worth it, this was just a quick start here.

2024-11-29 09:42 UTC, nejch commented on gitlab/client.py
> +                )
I'll put this into a helper so it's reused and we have a smaller diff to review here.

2024-12-03 13:57 UTC, max-wittig commented on gitlab/client.py
> +class _BaseGrapQL:
```suggestion
class _BaseGraphQL:
```

2024-12-03 13:58 UTC, max-wittig commented on gitlab/client.py
> +class GraphQL(_BaseGrapQL):
```suggestion
class GraphQL(_BaseGraphQL):
```

2024-12-03 13:59 UTC, max-wittig commented on gitlab/client.py
> +class AsyncGraphQL(_BaseGrapQL):
```suggestion
class AsyncGraphQL(_BaseGraphQL):
```

2024-12-03 14:00 UTC, max-wittig commented on tests/unit/test_graphql.py
> +def api_url():
```suggestion
def api_url() -> str:
```

2024-12-03 14:01 UTC, max-wittig requested changes
Let's fix some typos

2024-12-03 15:05 UTC, nejch commented
Thanks @max-wittig should be ready now :bow:

2024-12-04 13:28 UTC, merged

2024-12-17 12:30 UTC, roma-glushko commented
Hey folks, I have installed v5.1.0 and could not find the async client, so it must be not released yet.
When you do plan to include it in the next version of the client?

2024-12-17 12:38 UTC, roma-glushko commented
@nejch I would love to give it a try, so if it's not too much trouble to release sooner I would really appreciate that (at least a prerelease version if the pipeline you have supports that).

Otherwise, I can try to temporary pull it from the main branch.

2024-12-17 13:28 UTC, nejch commented
This is now released. There's a bit of blocking code in there for the retry logic AFAIK, so let us know if it doesn't work as expected.

2024-12-18 08:54 UTC, roma-glushko commented
@nejch Hey Nejc, this is awesome! Thank you for releasing it soo fast.
Gonna give it a try and let you know if there is anything.

> There's a bit of blocking code in there for the retry logic AFAIK, so let us know if it doesn't work as expected.

Okay, that's good to know :eye: I think this is fine for now. Do you guys have any plans to address that part?

2024-12-18 11:07 UTC, nejch commented
@roma-glushko for sure if we get any feedback from users as you most likely have more uses for this than ourselves at the moment :) It was mostly so we could reuse some sync/async client code.